./stepTest.bash ../../data/datatrees/data/tree01 ../../results/medians/trees/frechet/tree01/
./stepTest.bash ../../data/datatrees/data/tree02 ../../results/medians/trees/frechet/tree02/
./stepTest.bash ../../data/datatrees/data/tree03 ../../results/medians/trees/frechet/tree03/
./stepTest.bash ../../data/datatrees/data/tree04 ../../results/medians/trees/frechet/tree04/
./stepTest.bash ../../data/datatrees/data/tree05 ../../results/medians/trees/frechet/tree05/
./stepTest.bash ../../data/datatrees/data/tree06 ../../results/medians/trees/frechet/tree06/
./stepTest.bash ../../data/datatrees/data/tree07 ../../results/medians/trees/frechet/tree07/
./stepTest.bash ../../data/datatrees/data/tree08 ../../results/medians/trees/frechet/tree08/
./stepTest.bash ../../data/datatrees/data/tree09 ../../results/medians/trees/frechet/tree09/
./stepTest.bash ../../data/datatrees/data/tree10 ../../results/medians/trees/frechet/tree10/
./stepTest.bash ../../data/datatrees/data/tree11 ../../results/medians/trees/frechet/tree11/
./stepTest.bash ../../data/datatrajectory/paths/data01/ ../../results/medians/trajectory/frechet/median01/
./stepTest.bash ../../data/datatrajectory/paths/data02/ ../../results/medians/trajectory/frechet/median02/
./stepTest.bash ../../data/datatrajectory/paths/data03/ ../../results/medians/trajectory/frechet/median03/
./stepTest.bash ../../data/datatrajectory/paths/data04/ ../../results/medians/trajectory/frechet/median04/
./stepTest.bash ../../data/datatrajectory/paths/data05/ ../../results/medians/trajectory/frechet/median05/
./stepTest.bash ../../data/datatrajectory/paths/data06/ ../../results/medians/trajectory/frechet/median06/
./stepTest.bash ../../data/datatrajectory/paths/data07/ ../../results/medians/trajectory/frechet/median07/
./stepTest.bash ../../data/datatrajectory/paths/data08/ ../../results/medians/trajectory/frechet/median08/
./stepTest.bash ../../data/datatrajectory/paths/data09/ ../../results/medians/trajectory/frechet/median09/
./stepTest.bash ../../data/datatrajectory/paths/data10/ ../../results/medians/trajectory/frechet/median10/
./stepTest.bash ../../data/datatrajectory/paths/data11/ ../../results/medians/trajectory/frechet/median11/
./stepTest.bash ../../data/datatrajectory/paths/data12/ ../../results/medians/trajectory/frechet/median12/
